name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup-clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: setup-libvips
      run: |
        sudo apt-get install libvips42
        sudo apt-get install libvips-dev
        sudo apt-get install libomp-dev

    - name: make
      run: make
