name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup-clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: make
      run: make
